In [58]:
!pip install ucimlrepo
# !pip install --upgrade jupyter_client

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

## Importing libraries

In [59]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Getting dataset

In [60]:
retail_data = fetch_ucirepo(id=352)

In [61]:
cols_to_keep = ["InvoiceNo","StockCode","Description"]
retail_df = pd.DataFrame(retail_data.data.original)[cols_to_keep]
retail_df

       InvoiceNo StockCode                          Description
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...       ...                                  ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[541909 rows x 3 columns]

In [62]:
retail_df.value_counts()

InvoiceNo  StockCode  Description
555524     22698      PINK REGENCY TEACUP AND SAUCER         20
C544580    S          SAMPLES                                16
555524     22697      GREEN REGENCY TEACUP AND SAUCER        12
572861     22775      PURPLE DRAWERKNOB ACRYLIC EDWARDIAN     8
C553531    S          SAMPLES                                 7
                                                             ..
552803     21754      HOME BUILDING BLOCK WORD                1
           21755      LOVE BUILDING BLOCK WORD                1
           21792      CLASSIC FRENCH STYLE BASKET GREEN       1
           22066      LOVE HEART TRINKET POT                  1
           20728      LUNCH BAG CARS BLUE                     1
Name: count, Length: 529773, dtype: int64

## Removing null values items

In [63]:
retail_df.isna().sum()

InvoiceNo         0
StockCode         0
Description    1454
dtype: int64

In [64]:
retail_df = retail_df.dropna(subset=["Description"])
retail_df

       InvoiceNo StockCode                          Description
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...       ...                                  ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[540455 rows x 3 columns]

## Getting dataset info

In [65]:
retail_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540455 entries, 0 to 541908
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    540455 non-null  object
 1   StockCode    540455 non-null  object
 2   Description  540455 non-null  object
dtypes: object(3)
memory usage: 16.5+ MB

In [66]:
retail_df.describe()

       InvoiceNo StockCode                         Description
count     540455    540455                              540455
unique     24446      3958                                4223
top       573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER
freq        1114      2313                                2369

## Getting unique invoices and items

In [67]:
len(retail_df["InvoiceNo"].unique())

24446

In [68]:
len(retail_df["StockCode"].unique())

3958

## Removing items which haven't been purchased more than 250 times (as thier are many unique items)

In [69]:
item_counts = retail_df["StockCode"].value_counts()
retail_df = retail_df[retail_df["StockCode"].isin(item_counts[item_counts>=250].index)]
retail_df

       InvoiceNo StockCode                          Description
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...       ...                                  ...
541902    581587     22629                  SPACEBOY LUNCH BOX
541903    581587     23256          CHILDRENS CUTLERY SPACEBOY
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[315092 rows x 3 columns]

## Data cleaning

In [70]:
retail_df["StockCode"] = retail_df["StockCode"].str.replace(r"[^0-9]", "", regex=True)
retail_df = retail_df[~retail_df["InvoiceNo"].str.startswith("C")]
retail_df = retail_df[retail_df["StockCode"].astype(str).str.isnumeric()]

### Getting unique item code description

In [71]:
item_counts = retail_df['StockCode'].value_counts()
item_counts.describe()

count     623.000000
mean      493.428571
std       306.527970
min       227.000000
25%       302.000000
50%       388.000000
75%       561.500000
max      3888.000000
Name: count, dtype: float64

### Getting unique item name description

In [72]:
item_counts = retail_df['Description'].value_counts()
item_counts.describe()

count     770.000000
mean      399.228571
std       294.309467
min         1.000000
25%       263.000000
50%       353.000000
75%       492.000000
max      2260.000000
Name: count, dtype: float64

### Since item name and code count is different hence investigating further

In [73]:
retail_df.groupby("StockCode")["Description"].nunique().sort_values(ascending=False).head()

StockCode
84997    9
20713    8
23084    7
23343    5
21181    5
Name: Description, dtype: int64

### putting name of item for each item code which has max frequency

In [74]:
canonical_desc = (
    retail_df.groupby("StockCode")["Description"]
    .agg(lambda x: x.value_counts().idxmax())
)
retail_df["Description"] = retail_df["StockCode"].map(canonical_desc)

In [75]:
retail_df.groupby("StockCode")["Description"].nunique().sort_values(ascending=False).head()

StockCode
85199    1
15036    1
15056    1
16161    1
16237    1
Name: Description, dtype: int64

In [76]:
item_counts = retail_df['Description'].value_counts().sort_values(ascending=True)
item_counts

Description
CHILDS BREAKFAST SET SPACEBOY          227
TRIPLE HOOK ANTIQUE IVORY ROSE         234
PHOTO FRAME 3 CLASSIC HANGING          236
PANTRY ROLLING PIN                     239
PARISIENNE CURIO CABINET               242
                                      ...
LUNCH BAG RED RETROSPOT               1595
REGENCY CAKESTAND 3 TIER              2022
PARTY BUNTING                         2079
WHITE HANGING HEART T-LIGHT HOLDER    2271
JUMBO BAG RED RETROSPOT               3888
Name: count, Length: 623, dtype: int64

In [77]:
item_counts = retail_df['StockCode'].value_counts().sort_values()
item_counts

StockCode
22634     227
23146     234
22796     236
22978     239
23112     242
         ...
20725    1595
22423    2022
47566    2079
85123    2271
85099    3888
Name: count, Length: 623, dtype: int64

### Combining item codes if they have common item name

In [78]:
desc_to_codes = retail_df.groupby("Description")["StockCode"].nunique()
shared = desc_to_codes[desc_to_codes > 1]
print("Descriptions shared by multiple StockCodes:")
print(shared)

Descriptions shared by multiple StockCodes:
Series([], Name: StockCode, dtype: int64)

In [79]:
for desc in shared.index:
    codes = retail_df[retail_df["Description"] == desc]["StockCode"].unique()
    print(f"\nDescription: '{desc}' → StockCodes: {codes}")
    subset = retail_df[retail_df["Description"] == "COLOURING PENCILS BROWN TUBE"]
    dominant_code = subset["StockCode"].value_counts().idxmax()
    retail_df.loc[retail_df["Description"] == "COLOURING PENCILS BROWN TUBE", "StockCode"] = dominant_code

print("Unique StockCodes:", retail_df["StockCode"].nunique())
print("Unique Descriptions:", retail_df["Description"].nunique())

Unique StockCodes: 623
Unique Descriptions: 623

In [80]:
retail_df.value_counts()

InvoiceNo  StockCode  Description
555524     22698      PINK REGENCY TEACUP AND SAUCER         20
           22697      GREEN REGENCY TEACUP AND SAUCER        12
572861     22775      PURPLE DRAWERKNOB ACRYLIC EDWARDIAN     8
547498     84596      SMALL DOLLY MIX DESIGN ORANGE BOWL      7
574481     23084      RABBIT NIGHT LIGHT                      6
                                                             ..
553393     21843      RED RETROSPOT CAKE STAND                1
           21731      RED TOADSTOOL LED NIGHT LIGHT           1
           21531      RED RETROSPOT SUGAR JAM BOWL            1
           21428      SET3 BOOK BOX GREEN GINGHAM FLOWER      1
           21935      SUKI  SHOULDER BAG                      1
Name: count, Length: 297012, dtype: int64

In [81]:
retail_df

       InvoiceNo StockCode                          Description
0         536365     85123   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365     84406       CREAM CUPID HEARTS COAT HANGER
3         536365     84029  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365     84029  KNITTED UNION FLAG HOT WATER BOTTLE
...          ...       ...                                  ...
541902    581587     22629                  SPACEBOY LUNCH BOX
541903    581587     23256          CHILDRENS CUTLERY SPACEBOY
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[307406 rows x 3 columns]

## Converting the dataframe to one-hot format

In [82]:
retail_items_df = (
    pd.get_dummies(retail_df["StockCode"])
    .groupby(retail_df["InvoiceNo"])
    .max()  # max ensures binary 0/1
)
retail_items_df

,15036,15056,16161,16237,20675,20676,20677,20679,20685,20711,...,85014,85048,85049,85053,85066,85099,85123,85150,85152,85199
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
536366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536367,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536368,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
536369,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581580,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
581583,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
581585,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
581586,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
581587,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Importing libraries for apriory algo and rule mining

In [83]:
from mlxtend.frequent_patterns import apriori,association_rules
warnings.filterwarnings(
    "ignore",
    message="datetime.datetime.utcnow() is deprecated"
)
warnings.filterwarnings(
    "ignore",
    message="jupyter_client.session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC)."
)

### getting frequent itemsets

In [84]:
frequent_itemsets = apriori(
    retail_items_df,
    min_support=0.01,
    use_colnames=True
)

In [85]:
frequent_itemsets = frequent_itemsets.sort_values("support",ascending=False)
frequent_itemsets

       support                      itemsets
618   0.139978                       (85099)
619   0.116288                       (85123)
261   0.105102                       (22423)
557   0.097926                       (47566)
17    0.082573                       (20725)
...        ...                           ...
1299  0.010025                (22699, 22411)
630   0.010025                (20711, 21929)
847   0.010025                (20728, 22197)
1157  0.010025                (22192, 22193)
2035  0.010025  (20725, 20726, 22384, 22382)

[2064 rows x 2 columns]

### getting rules

In [86]:
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.6
)

rules = rules[rules['lift'] > 1]

rules = rules.sort_values("lift", ascending=False)

### getting non trivial rules (removing weak rules)

In [87]:
rules = rules[
    (rules['confidence'] >= 0.6) &
    (rules['lift'] > 1.2) &
    (rules['support'] >= 0.02)
]
rules = rules.sort_values(
    ["lift", "confidence", "support"],
    ascending=False
)

### frequent itemsets

In [88]:
frequent_itemsets

       support                      itemsets
618   0.139978                       (85099)
619   0.116288                       (85123)
261   0.105102                       (22423)
557   0.097926                       (47566)
17    0.082573                       (20725)
...        ...                           ...
1299  0.010025                (22699, 22411)
630   0.010025                (20711, 21929)
847   0.010025                (20728, 22197)
1157  0.010025                (22192, 22193)
2035  0.010025  (20725, 20726, 22384, 22382)

[2064 rows x 2 columns]

### rules

In [89]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
38,(22578),(22577),0.027067,0.028439,0.020472,0.756335,26.595218,1.0,0.019702,3.987287,0.989173,0.584337,0.749203,0.738093
37,(22577),(22578),0.028439,0.027067,0.020472,0.719852,26.595218,1.0,0.019702,3.472920,0.990570,0.584337,0.712058,0.738093
19,(22698),"(22699, 22697)",0.040416,0.040521,0.028597,0.707572,17.461730,1.0,0.026959,3.281075,0.982438,0.546371,0.695222,0.706650
17,"(22699, 22697)",(22698),0.040521,0.040416,0.028597,0.705729,17.461730,1.0,0.026959,3.260888,0.982546,0.546371,0.693335,0.706650
16,"(22699, 22698)",(22697),0.031604,0.053554,0.028597,0.904841,16.896019,1.0,0.026905,9.945990,0.971519,0.505597,0.899457,0.719416
12,(22697),(22698),0.053554,0.040416,0.033398,0.623645,15.430744,1.0,0.031234,2.549681,0.988111,0.551394,0.607794,0.725008
11,(22698),(22697),0.040416,0.053554,0.033398,0.826371,15.430744,1.0,0.031234,5.450962,0.974583,0.551394,0.816546,0.725008
18,"(22698, 22697)",(22699),0.033398,0.056244,0.028597,0.856240,15.223564,1.0,0.026719,6.564805,0.966595,0.468453,0.847673,0.682341
15,(23300),(23301),0.039994,0.048172,0.028808,0.720317,14.953079,1.0,0.026882,3.403235,0.971998,0.485333,0.706162,0.659173
33,"(22699, 22423)",(22697),0.027700,0.053554,0.021527,0.777143,14.511516,1.0,0.020043,4.246875,0.957615,0.360424,0.764533,0.589557
34,"(22423, 22697)",(22699),0.026856,0.056244,0.021527,0.801572,14.251584,1.0,0.020016,4.756154,0.955493,0.349614,0.789746,0.592155
13,(22698),(22699),0.040416,0.056244,0.031604,0.781984,13.903329,1.0,0.029331,4.328843,0.967163,0.485807,0.768991,0.671949
3,(22699),(22697),0.056244,0.053554,0.040521,0.720450,13.452901,1.0,0.037509,3.385611,0.980833,0.584920,0.704632,0.738550
4,(22697),(22699),0.053554,0.056244,0.040521,0.756650,13.452901,1.0,0.037509,3.878186,0.978044,0.584920,0.742147,0.738550
20,(22630),(22629),0.044848,0.047486,0.028386,0.632941,13.329038,1.0,0.026256,2.594990,0.968407,0.443894,0.614642,0.615359
35,(23200),(23199),0.031446,0.051601,0.021421,0.681208,13.201366,1.0,0.019799,2.974977,0.954258,0.347603,0.663863,0.548170
21,(22356),(20724),0.039202,0.054556,0.027542,0.702557,12.877724,1.0,0.025403,3.178574,0.959980,0.415936,0.685394,0.603696
28,(20723),(20724),0.038094,0.054556,0.025642,0.673130,12.338333,1.0,0.023564,2.892418,0.955345,0.382677,0.654268,0.571575
8,(22727),(22726),0.055453,0.051707,0.033768,0.608944,11.776850,1.0,0.030900,2.424954,0.968811,0.460101,0.587621,0.631003
7,(22726),(22727),0.051707,0.055453,0.033768,0.653061,11.776850,1.0,0.030900,2.722518,0.964984,0.460101,0.632693,0.631003
24,(20719),(20724),0.044056,0.054556,0.026698,0.605988,11.107632,1.0,0.024294,2.399531,0.951909,0.371240,0.583252,0.547675
14,(22910),(22086),0.043265,0.061204,0.029125,0.673171,10.998797,1.0,0.026477,2.872435,0.950191,0.386555,0.651863,0.574516
29,(22728),(22727),0.041313,0.055453,0.024798,0.600255,10.824587,1.0,0.022507,2.362876,0.946730,0.344575,0.576787,0.523724
40,"(20712, 85099)",(22386),0.033768,0.064264,0.020261,0.600000,9.336453,1.0,0.018091,2.339339,0.924098,0.260516,0.572529,0.457635
32,"(22386, 22411)",(85099),0.024693,0.139978,0.022266,0.901709,6.441801,1.0,0.018809,8.749791,0.866151,0.156354,0.885712,0.530387
39,"(22386, 20712)",(85099),0.022635,0.139978,0.020261,0.895105,6.394619,1.0,0.017092,8.198878,0.863156,0.142328,0.878032,0.519923
30,"(22386, 21931)",(85099),0.027172,0.139978,0.024060,0.885437,6.325550,1.0,0.020256,7.506973,0.865427,0.168142,0.866791,0.528659
31,"(21931, 22411)",(85099),0.027647,0.139978,0.023532,0.851145,6.080570,1.0,0.019662,5.777585,0.859299,0.163310,0.826917,0.509628
6,(21928),(85099),0.042526,0.139978,0.033821,0.795285,5.681509,1.0,0.027868,4.201078,0.860588,0.227466,0.761966,0.518449
26,(21733),(85123),0.039097,0.116288,0.025801,0.659919,5.674884,1.0,0.021254,2.598535,0.857303,0.199104,0.615168,0.440894
0,(22386),(85099),0.064264,0.139978,0.050599,0.787356,5.624864,1.0,0.041603,4.044429,0.878686,0.329327,0.752746,0.574417
36,(20711),(85099),0.027700,0.139978,0.020841,0.752381,5.375000,1.0,0.016964,3.473166,0.837142,0.141933,0.712078,0.450635
9,(20712),(85099),0.045534,0.139978,0.033768,0.741599,5.297975,1.0,0.027394,3.328247,0.849950,0.222531,0.699542,0.491418
23,(22385),(85099),0.036300,0.139978,0.026909,0.741279,5.295689,1.0,0.021827,3.324131,0.841722,0.180148,0.699169,0.466757
25,(20713),(85099),0.035034,0.139978,0.025853,0.737952,5.271919,1.0,0.020949,3.281924,0.839735,0.173329,0.695301,0.461324
22,(21930),(85099),0.037197,0.139978,0.027436,0.737589,5.269324,1.0,0.022229,3.277382,0.841525,0.183228,0.694878,0.466797
10,(21929),(85099),0.045639,0.139978,0.033451,0.732948,5.236172,1.0,0.027063,3.220429,0.847710,0.219834,0.689482,0.485961
1,(21931),(85099),0.062470,0.139978,0.045534,0.728885,5.207147,1.0,0.036789,3.172169,0.861793,0.290182,0.684758,0.527089
2,(22411),(85099),0.061995,0.139978,0.043687,0.704681,5.034232,1.0,0.035009,2.912179,0.854324,0.276000,0.656614,0.508390
5,(23199),(85099),0.051601,0.139978,0.034770,0.673824,4.813791,1.0,0.027547,2.636682,0.835370,0.221736,0.620736,0.461111
27,(22379),(85099),0.039466,0.139978,0.025801,0.653743,4.670334,1.0,0.020276,2.483771,0.818173,0.167926,0.597386,0.419031

### rules generated

In [90]:
print(rules.shape[0],"rules mined")

41 rules mined

### printing all rules

In [91]:
code_to_desc = (
    retail_df[['StockCode', 'Description']]
    .drop_duplicates()
    .set_index('StockCode')['Description']
    .to_dict()
)
def decode_items(itemset):
    return [code_to_desc.get(i, i) for i in itemset]

for _, row in rules.iterrows():

    antecedent = ", ".join(decode_items(row['antecedents']))
    consequent = ", ".join(decode_items(row['consequents']))

    print(f"({antecedent.lower()}) -> {consequent.lower()}")

(wooden star christmas scandinavian) -> wooden heart christmas scandinavian
(wooden heart christmas scandinavian) -> wooden star christmas scandinavian
(pink regency teacup and saucer) -> roses regency teacup and saucer , green regency teacup and saucer
(roses regency teacup and saucer , green regency teacup and saucer) -> pink regency teacup and saucer
(roses regency teacup and saucer , pink regency teacup and saucer) -> green regency teacup and saucer
(green regency teacup and saucer) -> pink regency teacup and saucer
(pink regency teacup and saucer) -> green regency teacup and saucer
(pink regency teacup and saucer, green regency teacup and saucer) -> roses regency teacup and saucer
(gardeners kneeling pad cup of tea ) -> gardeners kneeling pad keep calm
(roses regency teacup and saucer , regency cakestand 3 tier) -> green regency teacup and saucer
(regency cakestand 3 tier, green regency teacup and saucer) -> roses regency teacup and saucer
(pink regency teacup and saucer) -> roses regency teacup and saucer
(roses regency teacup and saucer ) -> green regency teacup and saucer
(green regency teacup and saucer) -> roses regency teacup and saucer
(dolly girl lunch box) -> spaceboy lunch box
(jumbo bag pears) -> jumbo bag apples
(charlotte bag pink polkadot) -> red retrospot charlotte bag
(strawberry charlotte bag) -> red retrospot charlotte bag
(alarm clock bakelike red ) -> alarm clock bakelike green
(alarm clock bakelike green) -> alarm clock bakelike red
(woodland charlotte bag) -> red retrospot charlotte bag
(paper chain kit vintage christmas) -> paper chain kit 50's christmas
(alarm clock bakelike pink) -> alarm clock bakelike red
(jumbo bag woodland animals, jumbo bag red retrospot) -> jumbo bag pink polkadot
(jumbo bag pink polkadot, jumbo shopper vintage red paisley) -> jumbo bag red retrospot
(jumbo bag pink polkadot, jumbo bag woodland animals) -> jumbo bag red retrospot
(jumbo bag pink polkadot, jumbo storage bag suki) -> jumbo bag red retrospot
(jumbo storage bag suki, jumbo shopper vintage red paisley) -> jumbo bag red retrospot
(jumbo bag scandinavian blue paisley) -> jumbo bag red retrospot
(red hanging heart t-light holder) -> white hanging heart t-light holder
(jumbo bag pink polkadot) -> jumbo bag red retrospot
(jumbo bag toys ) -> jumbo bag red retrospot
(jumbo bag woodland animals) -> jumbo bag red retrospot
(jumbo bag spaceboy design) -> jumbo bag red retrospot
(jumbo bag owls) -> jumbo bag red retrospot
(jumbo storage bag skulls) -> jumbo bag red retrospot
(jumbo bag pink vintage paisley) -> jumbo bag red retrospot
(jumbo storage bag suki) -> jumbo bag red retrospot
(jumbo shopper vintage red paisley) -> jumbo bag red retrospot
(jumbo bag apples) -> jumbo bag red retrospot
(recycling bag retrospot ) -> jumbo bag red retrospot